### ISSUE TITLE
Sinai Peninsula is colored instead of Israel on the Numpy users location map

### ISSUE THREAD

**Issue by holamgadol** [numpy/numpy-surveys#14]
![image](https://user-images.githubusercontent.com/20232096/141660953-c5b66244-a6f6-4e6c-8787-ace9d8633e4b.png)

Should be like on the image below:
![image](https://user-images.githubusercontent.com/20232096/141660934-2fa5d209-3c71-4c27-a924-c3134559173f.png)

**Comment by InessaPawson** [comment]
@holamgadol Thank you for your comment! I'll fix it in the nearest future.
